// <auto-generated />
using System;
using Eneru.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eneru.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513115006_UpdateProductImages")]
    partial class UpdateProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Eneru.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Eneru.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tops",
                            Slug = "tops"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bottoms",
                            Slug = "bottoms"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessories",
                            Slug = "accessories"
                        });
                });

            modelBuilder.Entity("Eneru.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Eneru.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Eneru.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Eneru Basics",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Essential everyday white t-shirt made from 100% organic cotton.",
                            ImageUrl = "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80",
                            IsAvailable = true,
                            Name = "Classic White Tee",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Eneru Denim",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern slim fit black denim with stretch comfort technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80",
                            IsAvailable = true,
                            Name = "Slim Black Jeans",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Eneru Sport",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean minimalist leather sneakers. Versatile and timeless.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80",
                            IsAvailable = true,
                            Name = "White Leather Sneakers",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Eneru Basics",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Relaxed fit hoodie in premium heavyweight fleece.",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
                            IsAvailable = true,
                            Name = "Oversized Hoodie",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Eneru Street",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Utility cargo pants with multiple pockets. Perfect for everyday wear.",
                            ImageUrl = "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&q=80",
                            IsAvailable = true,
                            Name = "Cargo Pants",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Eneru Accessories",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full grain leather belt with brushed silver buckle.",
                            ImageUrl = "https://images.unsplash.com/photo-1624222247344-550fb60fe8ff?w=800&q=80",
                            IsAvailable = true,
                            Name = "Leather Belt",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Eneru Sport",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight performance sneakers with responsive cushioning.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
                            IsAvailable = true,
                            Name = "Running Sneakers",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Eneru Accessories",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable canvas tote with internal zip pocket.",
                            ImageUrl = "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&q=80",
                            IsAvailable = true,
                            Name = "Canvas Tote Bag",
                            Price = 45.99m
                        });
                });

            modelBuilder.Entity("Eneru.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Eneru.Models.CartItem", b =>
                {
                    b.HasOne("Eneru.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eneru.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eneru.Models.Order", b =>
                {
                    b.HasOne("Eneru.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eneru.Models.OrderItem", b =>
                {
                    b.HasOne("Eneru.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eneru.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Eneru.Models.Product", b =>
                {
                    b.HasOne("Eneru.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Eneru.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Eneru.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Eneru.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
